//
// Updated on 11/12/25.
// Copyright © 2025. All rights reserved.///
/// @Generated by Mockolo
///

import Foundation
import LogStreamKit

public class LogStreamKitMock: LogStreamKit {
  // MARK: Lifecycle

  public init() {}

  // MARK: Public

  public private(set) var logEventCallCount = 0
  public var logEventHandler: ((String, [String: Any]?, LogLevel) -> Void)?
  public private(set) var logErrorCallCount = 0
  public var logErrorHandler: ((Error, [String: Any]?) -> Void)?
  public private(set) var flushCallCount = 0
  public var flushHandler: ((@escaping (Bool) -> Void) -> Void)?

  public func logEvent(_ name: String, params: [String: Any]?, level: LogLevel) {
    logEventCallCount += 1
    if let logEventHandler {
      logEventHandler(name, params, level)
    }
  }

  public func logError(_ error: Error, metadata: [String: Any]?) {
    logErrorCallCount += 1
    if let logErrorHandler {
      logErrorHandler(error, metadata)
    }
  }

  public func flush(completion: @escaping (Bool) -> Void) {
    flushCallCount += 1
    if let flushHandler {
      flushHandler(completion)
    }
  }
}
