#!/bin/bash

# OVERVIEW: Mockolo is a mock generator for Swift files.
# https://github.com/uber/mockolo

# USAGE EXAMPLES:
# Tools/generate-mocks

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source Tools/src-generate-mocks/log_stream_kit_mocks

generate() {
    echo -e "\n*** Step started: Generate mocks. ***\n"

    local CURDATE
    CURDATE=$(date +"%m/%d/%y")
    HEADER=$(echo -e "//\n// Updated on $CURDATE.\n// Copyright © 2025. All rights reserved.\n")
    generate_mocks_for_log_stream_kit_modules "$TOOL" "$HEADER" "$SRC_PATH"

    echo -e "\n*** Step finished: Generate mocks. ***\n"
}

error() {
    echo "*** Script was interrupted due to an error. ***"
    local MSG="$1"
    echo "ERROR: $MSG"
    exit 1
}

SRC_PATH="Sources/"
TOOL="$1"

if [[ -n "$TOOL" ]]; then
    echo "*** Using the provided executable of Mockolo. ***"
else
    which -s mockolo
    if (($? != 0)); then
        error "Please install Mockolo via Homebrew beforehand."
    else
        echo "*** Using the homebrew version of Mockolo. ***"
        TOOL="mockolo"
    fi
fi

Tools/src-utils/check-versions
generate
Tools/format-code
